AWSTemplateFormatVersion: "2010-09-09"
Description: Launch ALB 

Parameters:
  Environment:
    Description: "environment" 
    Type: String
    AllowedValues: ["DEVELOPMENT","PRODUCTION"]
    Default: "DEVELOPMENT"
  ResourceOwner:
    Description: "ResourceOwner"
    Type: String
    Default: "cloudNokku"
  ProjectName:
    Description: "Name of the Project" 
    Type: String
    Default: "ALB"

  AlbSubnets:
    Description: "subnets for launcing ALB" 
    Type: List<AWS::EC2::Subnet::Id>
  ResourceName:
    Description: "Name of the Resource used in ALB Name(backend)" 
    Type: String
    Default: "frontend"
  LoadBalancerSecurityGroup:
    Description: "security group attached to ALB"
    Type: String
    Default: "sg-062712bdd8be20072"
    
Resources:
  ApplicationLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Subnets: !Ref AlbSubnets
      Name: !Sub
        - ${ProjectName}-${ResourceName}-alb
        - {}
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Tags:
        - Key: 'Environment'
          Value: !Ref Environment
        - Key: 'ResourceOwner'
          Value: !Ref ResourceOwner
        - Key: 'ProjectName'
          Value: !Ref ProjectName