AWSTemplateFormatVersion: "2010-09-09"
Description: Launch ALB 

Parameters:
  Environment:
    Description: "environment" 
    Type: String
    AllowedValues: ["DEVELOPMENT","PRODUCTION"]
    Default: "DEVELOPMENT"
  ResourceOwner:
    Description: "ResourceOwner"
    Type: String
    Default: "cloudNokku"
  ProjectName:
    Description: "Name of the Project" 
    Type: String
    Default: "ALB"

  AlbSubnets:
    Description: "subnets for launcing ALB" 
    Type: List<AWS::EC2::Subnet::Id>
  ResourceName:
    Description: "Name of the Resource used in ALB Name(backend)" 
    Type: String
    Default: "frontend"
  LoadBalancerSecurityGroup:
    Description: "security group attached to ALB"
    Type: String
    Default: "sg-062712bdd8be20072"
    
  DefaultTargetGroupArn:
    Description: "Default Target group attached to ALB Listners"
    Type: String
    Default: ""

Conditions:
  HasTargetGroup: !Not [!Equals [!Ref DefaultTargetGroupArn, ""]]
  
Resources:
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Subnets: !Ref AlbSubnets
      Name: !Sub
        - ${ProjectName}-${ResourceName}-alb
        - {}
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Tags:
        - Key: 'Environment'
          Value: !Ref Environment
        - Key: 'ResourceOwner'
          Value: !Ref ResourceOwner
        - Key: 'ProjectName'
          Value: !Ref ProjectName

  HTTPListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions: !If
        - HasTargetGroup
        - - Order: 1
            Type: forward
            TargetGroupArn: !Ref DefaultTargetGroupArn
        - - FixedResponseConfig:
              ContentType: "text/plain"
              MessageBody: "Code: 503, service unavailable"
              StatusCode: "503"
            Type: "fixed-response"

  # SSLListener:
  #   Type: 'AWS::ElasticLoadBalancingV2::Listener'
  #   Properties:
  #     LoadBalancerArn: !Ref LoadBalancer
  #     Port: 443
  #     Protocol: HTTPS
  #     SslPolicy: "ELBSecurityPolicy-2016-08"
  #     Certificates:
  #       - CertificateArn: !Ref SsslCertificateArn
  #     DefaultActions: !If
  #       - HasTargetGroup
  #       - - Order: 1
  #           Type: forward
  #           TargetGroupArn: !Ref DefaultTargetGroupArn
  #       - - FixedResponseConfig:
  #             ContentType: "text/plain"
  #             MessageBody: "Code: 503, service unavailable"
  #             StatusCode: "503"
  #           Type: "fixed-response"  